### ISSUE TITLE
Setup.exe is missing from the latest release

### ISSUE THREAD

**Issue by bvwells** [nickform/pull-request-monitor#15]
Setup.exe is missing from the latest release :-(

https://github.com/nickform/pull-request-monitor/releases/tag/v1.2.0

**Comment by nickform** [comment]
Thanks for the issue! I noticed the same thing last night.

The build for v1.2.0 has expired so I can't get that file back. I could rebuild the whole thing but I'm not sure how the Squirrel auto-update stuff would react to that. The good news though is that v1.3.0 is now released so at least people following the latest release link from the readme (or elsewhere) will get to a page with a Setup.exe on it again.
