### ISSUE TITLE
How to install?  No setup.exe file exists.

### ISSUE THREAD

**Issue by szalapski** [nickform/pull-request-monitor#21]
Looks promising, @nickform.  Thanks for making this available.

The directions say to run Setup.exe, but it seems there isn't such a file in the zip.  Any ideas?  Am I expected to build it myself?

**Comment by nickform** [comment]
I'm afraid this repository is in a state of disrepair and I no longer have time to maintain it. I think that there was a problem with the build that for some reason meant that it did not produce a Setup.exe on the most recent PR and that is why the most recent release does not have that file. It's possible that if you use the Setup.exe from the last release but one, that it would update itself to the latest release but I'm not sure. In any case, I won't be able to support this or make any of the many improvements it would need to be really useful or even to keep up with API changes. I should probably update the README to make this clear to future visitors.
